### ISSUE TITLE
As a site administrator, I want to understand how other similar organizations are handling content so that I can make informed decisions about what appears to work well and what doesn't. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#11]
## User story
As a site administrator, I want to understand how other similar organizations are handling content so that I can make informed decisions about what appears to work well and what doesn't.
  
## Acceptance criteria
- [x] Begin researching comparable solutions. 
- [x] Document comparable solutions. 
- [x] Create a matrix for a comparative analysis of other science sites/resources. 
- [x] Conduct a first draft scoring of the comparative analysis. 

## Definition of done
- [x] A first draft of the comparative analysis is completed. 
- [x] The draft has been circulated for comment. 
- [x] Major conclusions are communicated to the NSF team.

**Comment by kategarklavs** [comment]
Howdy all! I've started working on the first few steps of this issue here:

https://docs.google.com/a/gsa.gov/spreadsheets/d/1uix2p1eINR5_STC9JblnOHrD4OUjzd5m7Zj1plgWTvQ/edit?usp=sharing

(General observations are in the Notes tab, and I've started the assessment in the Analysis tab.)

I'm going to be OOO for the rest of this week & am wondering if other folks would want to help out with the analysis — @line47 @austinhernandez @onezerojeremy @coreycaitlin, any interest? (If not, that's also totally fine: I'm happy to pick this back up next week; I just want to make sure I'm not a blocker.)

And a sidenote - I've never actually done a comparative analysis before, so I'd welcome your feedback/edits!

**Comment by kategarklavs** [comment]
Posted this in the channel, but I'll post here too — here's a doc (linked in the spreadsheet) with the observations/recommendations/points for consideration: 

https://docs.google.com/a/gsa.gov/document/d/1SwohF9Ea0lSUcSTRe0cq9tRrQUZTNWeWOXC8btMIhpc/edit?usp=sharing

As always, please feel free to add as you see fit!

**Comment by OpenGlobe** [comment]
Notes from standup: 

- We're ready for feedback on this task.

**Comment by kategarklavs** [comment]
Thank you all for sharing your feedback — it was most helpful (& I've incorporated your comments/suggestions) 😎 I'm going to move this card to the "Highlights" column, as I think the sheet + observations doc are ready to share with NSF tomorrow. (And, of course, I'm happy to keep tinkering with both; that said, both are in shareable shape as is.)

**Comment by kategarklavs** [comment]
We shared highlights from this doc w/the NSF team on Friday (8/11). After our meeting, I shared the observations doc. Going to move this to completed, for now, but I can definitely re-open this if the NSF team would like us to look at additional competitors.
