### ISSUE TITLE
As a designer / strategist, I want a style guide / design guide / content guide so that we have a uniform way of delivering product. 

### ISSUE THREAD

**Issue by OpenGlobe** [18F/nsf#12]
## User story
As a designer / strategist, I want a style guide / design guide / content guide so that we have a uniform way of delivering product. 
  
## Acceptance criteria
- [ ]
- [ ]
- [ ]

## Definition of done
- [ ]
- [ ]
- [ ]

**Comment by kategarklavs** [comment]
@OpenGlobe Hey! I just saw that this issue was opened/closed while I was out 😌 @coreycaitlin did share an existing NSF content guide with us (it's in the Drive folder), but there's definitely the possibility to incorporate principles from the 18F content guide into that existing guide, if time permits — thoughts on this?

**Comment by OpenGlobe** [comment]
Great!  I think this one was closed in favor of #14 since it appeared to be a duplicate - but feel free to revise / reopen if that was incorrect!

**Comment by kategarklavs** [comment]
@OpenGlobe Ah, OK! (I hadn't seen #14 😁 ) - I'll track my progress there!
